KTB-08
alexlenkov-ptn/KotlinTgBot pull request #6
Opened 2024-08-11 11:46 UTC by alexlenkov-ptn

2024-08-12 04:22 UTC, kaznikit requested changes

2024-08-12 04:22 UTC, kaznikit commented on src/main/kotlin/files.kt
>      while (true) {
Мне кажется бесконечный цикл здесь лишний. Также по возможности нужно стараться избегать таких циклов, чтобы предотвратить возможные утечки памяти

2024-08-12 04:22 UTC, kaznikit commented on src/main/kotlin/files.kt
> +        while (unlearnedWords.count() < INT_ANSWER_OPTIONS) {
Изменять коллекцию и при этом по ней же итерироваться является плохим тоном) Это может работать некорректно, лучше использовать дополнительный список для таких операций

2024-08-12 04:22 UTC, kaznikit commented on src/main/kotlin/files.kt
>              while (!unlearnedWords.contains(randomWord)) {
Здесь также обойтись без цикла

2024-08-12 04:22 UTC, kaznikit commented on src/main/kotlin/files.kt
> +        val secretWord = unlearnedWordsOptions.filter { it.correctAnswersCount < INT_CORRECT_ANSWER }.random().original
А здесь обязательно делать `random().original`? Может хватить просто `random()`

2024-08-12 04:22 UTC, kaznikit commented on src/main/kotlin/files.kt
> +        if (userInput == INT_NULL) {
В случае когда `userInput` равен -1 что будет происходить?

2024-08-12 06:10 UTC, alexlenkov-ptn commented on src/main/kotlin/files.kt
>      while (true) {
Скорректировал

2024-08-13 06:51 UTC, alexlenkov-ptn commented on src/main/kotlin/files.kt
>              while (!unlearnedWords.contains(randomWord)) {
Цикл заменил на If

2024-08-13 07:35 UTC, alexlenkov-ptn commented on src/main/kotlin/files.kt
> +        while (unlearnedWords.count() < INT_ANSWER_OPTIONS) {
Изменил подход к решению задачи. Удалил циклы while, т.к. тяжело читается конструкция, плюс не нашёл способ как НЕ использовать коллекцию без изменения внутри цикла без нагромождения переменных

2024-08-13 18:42 UTC, alexlenkov-ptn commented on src/main/kotlin/files.kt
> +        if (userInput == INT_NULL) {
Тут указал -1, чтобы котлин в дальнейшем позволил мне корректно работать с этой переменной, т.к. помню не давал возможности вычесть единицу, чтобы мэтчить ответ пользователя и индекс в списке. 
Сейчас указал цикл WHILE на случай если юзер ничего не вводит в консоль

2024-08-13 18:49 UTC, alexlenkov-ptn commented on src/main/kotlin/files.kt
> +        val secretWord = unlearnedWordsOptions.filter { it.correctAnswersCount < INT_CORRECT_ANSWER }.random().original
скорректировал

2024-08-14 07:09 UTC, kaznikit commented on src/main/kotlin/files.kt
> +    while (unlearnedWordsList.isNotEmpty()) {
а зачем здесь цикл? мы же `unlearnedWordsList` не изменяем в цикле, кажется что можно заменить на if

2024-08-14 07:09 UTC, kaznikit commented on src/main/kotlin/files.kt
> +        val unlearnedWordsMutableList = unlearnedWordsList.toMutableList()
не можем напрямую с `unlearnedWordsList` работать? он же тоже мутабельный

2024-08-14 16:09 UTC, alexlenkov-ptn commented on src/main/kotlin/files.kt
> +        val unlearnedWordsMutableList = unlearnedWordsList.toMutableList()
Изначально планировал unlearnedWordsList, видимо забыл удалить приведение к мутабельному типу. 

Как будто бы не можем, потому что изменяем этот список внутри цикла. Ранее было инфо, что изменять список и использовать его в условии while нехорошая практика, поэтому и заменил на другую переменную

2024-08-14 16:11 UTC, alexlenkov-ptn commented on src/main/kotlin/files.kt
> +    while (unlearnedWordsList.isNotEmpty()) {
По условии задачи KTB-07 необходим цикл, иначе у нас после первого ответа программа остановится

2024-08-15 06:30 UTC, kaznikit approved these changes

2024-08-15 06:30 UTC, kaznikit commented on src/main/kotlin/files.kt
> +        val unlearnedWordsMutableList = unlearnedWordsList.toMutableList()
Да, ок, все корректно

2024-08-15 08:38 UTC, merged