KTB-09
alexlenkov-ptn/KotlinTgBot pull request #7
Opened 2024-08-19 07:06 UTC by alexlenkov-ptn

2024-08-20 07:16 UTC, kaznikit requested changes

2024-08-21 04:17 UTC, alexlenkov-ptn commented on src/main/kotlin/files.kt
> +                        return break
Ага, тут скорректировал

2024-08-21 04:20 UTC, alexlenkov-ptn commented on src/main/kotlin/files.kt
> +                        userInput = readln().toIntOrNull() ?: null
Тут производим эту операцию в случае если пользователь не ввёл число или ввел что-то помимо числа. Это сообщение будет выводиться до тех пор, пока юзер не введет тип данных Int

2024-08-21 04:23 UTC, alexlenkov-ptn commented on src/main/kotlin/files.kt
> +                    var userInput = readln().toIntOrNull()
По моей логике мы тут ждём от юзера ответ на вопрос тренажёра

2024-08-21 04:29 UTC, alexlenkov-ptn commented on src/main/kotlin/LearnWordsTrainer.kt
> +    fun checkAnswer(userAnswerIndex: Int?): Boolean {
Ага, скорректировал

2024-08-21 04:38 UTC, alexlenkov-ptn commented on src/main/kotlin/files.kt
> +                    if (trainer.checkAnswer(userInput.minus(INT_ONE))) {
Если речь про строчку:
userInput = readln().toIntOrNull() ?: null
То тут скорректировал

Если про блок if, то мы ранее обрабатываем null, т.е. исключаем шанс, когда переменная userInput будет иметь значение null

2024-08-21 04:39 UTC, alexlenkov-ptn commented on src/main/kotlin/menu.kt
> +    fun MutableList<Word>.filter(): Int {
Этот файл к коду не относится, удалил

2024-08-22 05:12 UTC, kaznikit approved these changes

2024-08-24 10:14 UTC, merged