KTB-10
alexlenkov-ptn/KotlinTgBot pull request #8
Opened 2024-08-26 18:50 UTC by alexlenkov-ptn

2024-08-30 05:28 UTC, kaznikit requested changes

2024-08-30 05:28 UTC, kaznikit commented on src/main/kotlin/files.kt
> +@file:Suppress("UNUSED_CHANGED_VALUE", "NAME_SHADOWING")
давай попробуем убрать эти суппресы, нужно стараться использовать их только в крайних случаях

2024-08-30 06:32 UTC, alexlenkov-ptn commented on src/main/kotlin/files.kt
> +@file:Suppress("UNUSED_CHANGED_VALUE", "NAME_SHADOWING")
Скорректировал

2024-08-31 07:26 UTC, kaznikit approved these changes

2024-08-31 08:30 UTC, merged